title: PETER CHEGE - SOFTWARE ENGINEER
profile_img: /assets/img/profile.png
icon_img: /assets/img/icon.webp

name: "PETER KAMAU CHEGE"
job: "SOFTWARE ENGINEER"

phone_number: +254 726827902
address: Nairobi, Kenya
email: emchegep@gmail.com
linkedin_username: linkedin
github_username: emchegep
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
